CREATE TABLE "InternshipDetails" (
	"ID" serial PRIMARY KEY NOT NULL,
	"title" text NOT NULL,
	"sector" text NOT NULL,
	"state" text NOT NULL,
	"district" text NOT NULL,
	"benefits" text[],
	"candidatesapplied" integer NOT NULL,
	"companylogo" text,
	"companyname" text,
	"noofopportunities" integer,
	"description" text,
	"addressline1" text,
	"addrssline2" text,
	"zip" integer,
	"village" text,
	"minimumqualification" text,
	"course" text,
	"specialization" text,
	"certifications" text,
	"skills" text[],
	"spclrequirements" text,
	"stipend" text,
	"duration" text
);
